swagger: "2.0"
info:
  description: Cummins Documentation for backend implementation
  version: "1.0.1"
  title: Cummins Docs
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /bus_times:
    get:
      tags:
        - Bus Checkin Times
      summary: Read List of current Bus Times
      description: Read List of current Bus Times
      operationId: bus_times.read_bus_times
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              lpn_id:
                type: string
              rssi:
                type: number
              bus_name:
                type: string
              mac:
                type: string
              bus_type:
                type: string
    
    delete:
      tags:
        - Bus Checkin Times
      parameters:
        - name: entry_id
          description: ID of the Entry to delete
          in: query
          required: true
          type: number

      summary: Delete Bus Checkin Time
      description: Delete Bus Checkin Time
      operationId: bus_times.delete_bus_entry
      responses:
        200:
          description: Success

  /bus_names:
    post:
      tags:
        - Bus Names and Numbers
      summary: Add Bus Names (Numbers)
      description: Add Bus Names (Numbers)
      operationId: bus_numbers.add_bus_name
      parameters:
        - name: bus_name
          description: Number of Bus
          in: query
          type: string
          required: true
        - name: bus_type
          description: Type of bus (big, small)
          in: query
          type: string
          required: true
        - name: lpn_id
          description: ID of LPN of that bus
          in: query
          type: string
          required: true
      responses:
        200:
          description: Success

  /rssi_limit:
    get:
      tags:
        - RSSI Limit
      summary: Read current RSSI limit for entry
      description: Read current RSSI limit for entry
      operationId: rssi_limit.read_limit
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              rssi:
                type: number

    post:
      tags:
        - RSSI Limit
      summary: Set current RSSI limit for entry
      description: Set current RSSI limit for entry
      operationId: rssi_limit.set_limit
      parameters:
        - name: rssi
          type: number
          description: RSSI to set
          required: true
          in: query
      responses:
        200:
          description: Success


              