swagger: "2.0"
info:
  description: ISAE Documentation for backend implementation
  version: "1.0.1"
  title: ISAE Docs
consumes:
  - application/json
produces:
  - text/html

basePath: /

# Paths supported by the server application
paths:
  /bus_times:
    get:
      tags:
        - Bus Checkin Times
      summary: Read List of current Bus Times
      description: Read List of current Bus Times
      operationId: bus_times.read_bus_times
      responses:
        200:
          description: Success
          schema:
            type: object
            properties:
              lpn_id:
                type: string
              rssi:
                type: number
              bus_name:
                type: string
              mac:
                type: string
              bus_type:
                type: string